import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Forms in React</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen flex items-center justify-center">
        <form className="bg-white flex rounded-lg w-1/2">
          <div className="flex-1 text-gray-700">
            <h1>Let's Get Started.</h1>
            <p>
              Sign up today to join the smartest, simplest and slickest SaaS
              subscription template provider in the world.
            </p>
          </div>
          <div className=""></div>
        </form>
      </main>
    </div>
  );
}
